version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_USER_ID: $APP_USER_ID
        APP_GROUP_ID: $APP_GROUP_ID
    restart: always
    expose:
      - $APP_PORT
    ports:
      - $APP_PORT:$APP_PORT
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: "postgres:latest"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT

volumes:
  postgres_data:
